### ISSUE TITLE
Freight migration to another server

### ISSUE THREAD

**Issue by Dancho80** [freight-team/freight#89] opened 2018-06-20 07:01 UTC
Do you have some kind of wiki/man for migrating a freight repo from one server to another? Just copy some folder(s)?

**Comment by mmoll** [comment] 2018-06-20 15:30
Yes, rsync -aH or similar should do the job.

**Comment by Dancho80** [comment] 2018-06-21 05:42
Thanks!
what folders should we move?
VARLIB or
VARCACHE
or both of them?

**Comment by mmoll** [comment] 2018-06-21 08:18
VARLIB alone and rebuilding the repos would probably suffice, but if you have the opportunity to just sync both, that's easier anyway.

**Comment by mmoll** [comment] 2018-06-21 08:19
@Dancho80 closing this issue, please reopen, if something isn't turning out as intended.

**Closed by mmoll** 2018-06-21 08:19 UTC
